C
C  maximum variable types and number etc.
C
      INTEGER ID_RHO
      INTEGER ID_GAMMA
      INTEGER ID_TAU
      INTEGER ID_LAP
      INTEGER ID_EXRHO
      INTEGER MAX_VAR_TYPE 
      INTEGER MAX_VAR_NUM
      PARAMETER(ID_RHO       = 1)
      PARAMETER(ID_GAMMA     = 2)
      PARAMETER(ID_TAU       = 3)
      PARAMETER(ID_LAP       = 4)
      PARAMETER(ID_EXRHO     = 5)
      PARAMETER(MAX_VAR_TYPE = 5)
      PARAMETER(MAX_VAR_NUM  = 11)

